# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/yaroc/pb/status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/yaroc/pb/status.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x0c\x44isconnected\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\"G\n\x0eSignalStrength\x12\x0b\n\x03\x63sq\x18\x01 \x01(\r\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"U\n\x0cMiniCallHome\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\x12\x0c\n\x04\x66req\x18\x04 \x01(\r\x12\x10\n\x08min_freq\x18\x05 \x01(\r\x12\x10\n\x08max_freq\x18\x06 \x01(\r\"\x8b\x01\n\x06Status\x12%\n\x0c\x64isconnected\x18\x01 \x01(\x0b\x32\r.DisconnectedH\x00\x12*\n\x0fsignal_strength\x18\x02 \x01(\x0b\x32\x0f.SignalStrengthH\x00\x12\'\n\x0emini_call_home\x18\x03 \x01(\x0b\x32\r.MiniCallHomeH\x00\x42\x05\n\x03msgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.yaroc.pb.status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISCONNECTED._serialized_start=62
  _DISCONNECTED._serialized_end=97
  _SIGNALSTRENGTH._serialized_start=99
  _SIGNALSTRENGTH._serialized_end=170
  _MINICALLHOME._serialized_start=172
  _MINICALLHOME._serialized_end=257
  _STATUS._serialized_start=260
  _STATUS._serialized_end=399
# @@protoc_insertion_point(module_scope)
