# minicallhome_interval = 30           # Mini-call-home status interval in seconds

[modem]
apn = "internet.iot"   # The APN of your SIM card
rat = "NB-IoT"         # Radio Access Technology: "NB-IoT", "LTE-M", or "both"
# rat = "LTE-M"

[modem.bands]
ltem = [20]            # LTE-M frequency bands
nbiot = [20]           # NB-IoT frequency bands

# Optional MQTT configuration (if omitted, default settings are used)
# [mqtt]
# url = "mqtt.example.com"
# port = 1883
# packet_timeout = 10                  # Packet transmission timeout in seconds
