name: Linux Python CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: ./python

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.11', '3.14']
    steps:
      - uses: actions/checkout@v5
      - name: Install uv with all available options
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.10.12'
          python-version: ${{ matrix.python_version }}
          enable-cache: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: -r --out dist --find-interpreter --strip --compatibility pypi
          sccache: true
          working-directory: "python"
          manylinux: 2_28
          before-script-linux: yum install -y systemd-devel
      - name: Test the wheel
        run: |
          uv venv
          uv pip install -r pyproject.toml --extra dev
          uv pip install yaroc --pre --find-links dist
          source .venv/bin/activate
          pytest
      - name: Lint with ruff
        run: |
          uv tool install ruff
          ruff check . --select=E9,F63,F7,F82 --statistics
          ruff check . --exit-zero --statistics
          ruff format --check
      - name: Upload wheels
        if: matrix.python_version == '3.11'
        uses: actions/upload-artifact@v6
        with:
          name: wheels-linux-x86_64
          path: python/dist

  linux-cross:
    name: linux-cross (${{ matrix.target }})
    runs-on: ubuntu-latest
    container: rust:bullseye
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            arch: arm64
            pkg_config_path: /usr/lib/aarch64-linux-gnu/pkgconfig
            artifact_name: wheels-linux-aarch64
          - target: armv7-unknown-linux-gnueabihf
            arch: armhf
            pkg_config_path: /usr/lib/arm-linux-gnueabihf/pkgconfig
            artifact_name: wheels-linux-armv7
          - target: arm-unknown-linux-gnueabihf
            arch: armhf
            pkg_config_path: /usr/lib/arm-linux-gnueabihf/pkgconfig
            artifact_name: wheels-linux-armv6
    steps:
      - uses: actions/checkout@v5
      - name: Install libudev-dev
        run: |
          dpkg --add-architecture ${{ matrix.arch }}
          apt-get update
          apt-get install -y libudev-dev:${{ matrix.arch }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.10.12'
      - name: Build wheel
        working-directory: "python"
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_PATH: ${{ matrix.pkg_config_path }}
        run: |
          uv venv
          uv pip install "maturin[patchelf]" ziglang
          export PATH="$PWD/.venv/bin:$PATH"
          rustup target add ${{ matrix.target }}
          maturin build -r --strip --target ${{ matrix.target }} --zig --out dist --compatibility pypi
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact_name }}
          path: python/dist

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          working-directory: "python"
      - name: Upload sdist
        uses: actions/upload-artifact@v6
        with:
          name: wheels-sdist
          path: python/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [linux, linux-cross, sdist]
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Publish to PyPI
        working-directory: .
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish dist/*
