name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Packages
      run: sudo apt update && sudo apt install -y cargo protobuf-compiler libdbus-1-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Cargo format
      run: cargo fmt --check
    - name: Run tests
      run: cargo test --verbose
