name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Packages
      run: sudo apt update && sudo apt install -y protobuf-compiler libdbus-1-dev pkg-config
    - name: Build
      run: |
        rustup update --no-self-update stable
        rustup target add thumbv7em-none-eabihf
        cargo build -p yaroc-nrf52840 --target thumbv7em-none-eabihf
        cargo build --verbose
    - name: Cargo format
      run: cargo fmt --check
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy -- -D warnings
